#!/usr/bin/env bash

selected=$(find $@ -mindepth 1 -maxdepth 1 -type d -not -path "*/.git" | fzf)

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . -)

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $selected

	if [[ -f "$selected/.tmux" ]]; then
		cd "$selected"
		tmux source -t $selected_name "$selected/.tmux"
	fi
fi

tmux switch-client -t $selected_name
