#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	folders=$1
else
	devel="/media/storage/development"
	folders="$HOME/dotfiles/.config $devel/maya/ $devel/godot"
fi

selected=$(find $folders -mindepth 1 -maxdepth 1 -type d -not -path "*/.git" | fzf)

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . -)

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $selected

	if [[ -f "$selected/.tmux" ]]; then
		cd "$selected"
		tmux source -t $selected_name "$selected/.tmux"
	fi
fi

tmux switch-client -t $selected_name
