#!/usr/bin/env bash

SESSION_NAME=$1
PATHS="${@:2}"

tmux new-session -ds $SESSION_NAME "${BASH_SOURCE[0]} $SESSION_NAME $PATHS" &>/dev/null

if [[ -z "$TMUX" ]]; then
    tmux attach -t $SESSION_NAME &>/dev/null
else
    tmux switch-client -t $SESSION_NAME
fi

CURRENT_SESSION=$(tmux display-message -p '#S')
[[ "$CURRENT_SESSION" != "$SESSION_NAME" ]] && exit 0

selected=$(find $PATHS -mindepth 1 -maxdepth 1 -type d -not -path "*/.git" |
    fzf --preview 'ls -1 --color always {}' --preview-window=bottom,40%)

[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr . -)

tmux new-session -ds $selected_name -c $selected
tmux switch-client -t $selected_name
