#!/usr/bin/env bash

STEP="${2:-5%}"
LIMIT="1.0"

case $1 in
up)
	wpctl set-volume -l "$LIMIT" @DEFAULT_AUDIO_SINK@ "$STEP"+
	;;
down)
	wpctl set-volume @DEFAULT_AUDIO_SINK@ "$STEP"-
	;;
mute)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
	;;
*)
	echo "Usage: $0 {up|down|mute}"
	exit 1
	;;
esac
