#!/bin/bash

cat >/tmp/patch <<EOL
--- activate.fish       2024-10-29 22:14:54.895552387 +0300
+++ activate.patched.fish       2024-10-29 22:15:52.398034416 +0300
@@ -74,6 +74,10 @@
         functions -e _bashify_path
         functions -e _fishify_path
     end
+
+    if [ "\$TMUX" ]
+        tmux set-environment -r VIRTUAL_ENV
+    end
 end

 # Unset irrelevant variables.
@@ -122,3 +126,7 @@

     set -gx _OLD_FISH_PROMPT_OVERRIDE "$VIRTUAL_ENV"
 end
+
+if [ "\$TMUX" ]
+    tmux set-environment VIRTUAL_ENV $VIRTUAL_ENV
+end
EOL

if [-f $PWD/.venv/bin/activate.fish ]
	patch /tmp/patch > $PWD/.venv/bin/activate.fish
	rm /tmp/patch
end
