---
- name: 'Nemo | Checking for Distribution Config: {{ ansible_distribution }}'
  ansible.builtin.stat:
    path: '{{ role_path }}/tasks/{{ ansible_distribution }}.yml'
  register: wezterm_distribution_config

- name: 'Nemo | Run Tasks: {{ ansible_distribution }}'
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yml'
  when: wezterm_distribution_config.stat.exists

- name: Nemo | Creating directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - ~/.local/share
    - ~/.local/share/nemo

- name: Nemo | Linking Config
  ansible.builtin.file:
    src: '{{ role_path }}/files/actions'
    dest: ~/.local/share/nemo/actions
    state: link
