"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
hovered = { bg = "#272830", bold = true }
preview_hovered = { underline = false }
find_keyword = { fg = "red", bold = true, italic = true }
tab_active = { fg = "blue", bold = true }
tab_inactive = { fg = "darkgray", bold = false }
border_style = { fg = "black" }
border_symbol = "┃"
count_copied = { fg = "black", bg = "green", bold = true }
count_cut = { fg = "black", bg = "red", bold = true }
count_selected = { fg = "black", bg = "yellow", bold = true }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "darkgray", bg = "black" }

[mode]
normal_main = { bg = "blue", fg = "black", bold = true }
normal_alt = { fg = "blue", bg = "black", bold = true }
select_main = { fg = "green", bg = "black", bold = true }
select_alt = { bg = "green", fg = "black", bold = true }

[icon]
prepend_dirs = [
	{ name = "maya", text = "" },
	{ name = "dotfiles", text = "󱁿" },
	{ name = "Templates", text = "󱉟" },
	{ name = "Games", text = "" },
]
