#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find /media/storage/development/python -mindepth 1 -maxdepth 1 -type d | fzf --reverse --border)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
# tmux_running=$(pgrep tmux)

function poetry {
  if [ -f $selected/pyproject.toml ] ; then
    tmux send "poetry shell" ENTER
    sleep 0.4
    tmux send "clear" ENTER
  fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -A -s $selected_name 
    exit 0
fi

tmux new-session -d -s $selected_name -c $selected
poetry
tmux attach



