---
- name: GTK-Theme | Installing
  become: true
  with_items:
    - orchis-theme-git
    - kvantum-theme-orchis-git
    - kvantum-theme-materia
    - nordic-theme
    - nordic-darker-theme
  community.general.pacman:
    name: '{{ item }}'
  changed_when: false
