---
- name: Plymouth | Installing
  become: true
  community.general.pacman:
    name: plymouth
    state: present
  changed_when: false

- name: Plymouth | Modifying grub
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT=
    line: GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash rd.udev.log_priority=3
      vt.global_cursor_default=0"

- name: Plymouth | Modifying grubs splash screen
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT=
    line: GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash rd.udev.log_priority=3
      vt.global_cursor_default=0"

- name: Plymouth | Finding if plymouth allready in mkinitcpio
  ansible.builtin.shell: cat /etc/mkinitcpio.conf
  register: file_desc

- name: Plymouth | Modify mkinitcpio.conf
  become: true
  ansible.builtin.replace:
    path: /etc/mkinitcpio.conf
    regexp: \budev
    replace: udev plymouth
  when:
    - file_desc.stdout.find('plymouth') == -1

- name: Grub | Modifying timeout
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_TIMEOUT=
    line: GRUB_TIMEOUT=3

- name: Grub | Modifying timeout style
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_TIMEOUT_STYLE=
    line: GRUB_TIMEOUT_STYLE='hidden'

- name: Plymouth | Updating grub
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  become: true

- name: Plymouth | Setting theme
  ansible.builtin.command: plymouth-set-default-theme -R spinner
  become: true
