#!/usr/bin/env bash

ROFI_MENU=${1:-soundDevice.rasi}

sinks=$(pactl list short sinks | awk '{print $1}')
mapfile sinksArray < <(echo "$sinks")
entries=$(pactl list sinks | grep "device.description" | grep -oP '(?<=")[^"]*')
selected=$(echo "$entries" | rofi -dmenu -i -theme-str "@import '$ROFI_MENU'" -p "Audio Output" -format 'i')

if [[ -n $selected ]]; then
    sink=${sinksArray[$selected]}
    pactl set-default-sink "$sink"
fi
