#!/usr/bin/env bash

DISPLAY_SERVER="$XDG_SESSION_TYPE"

case "$DISPLAY_SERVER" in
wayland)
    brave-browser --disable-features=WaylandFractionalScaleV1 "$@"
    ;;
*)
    brave-browser "$@"
    ;;
esac
