---
- name: Fish | Install
  become: true
  loop:
    - fish
    - fisher
  loop_control:
    loop_var: package
  community.general.pacman:
    name: '{{ package }}'
    state: present
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Fish | Setup for user
  become: true
  user:
    name: '{{ ansible_user_id }}'
    shell: /bin/fish
