---
- name: Software | Install
  become: true
  loop:
    - dunst
    - lazygit
    - mpv
    - neovim
    - picom
    - rofi
    - starship
    - tmux
    - wezterm
    - yazi

  community.general.pacman:
    name: '{{ item }}'
    state: present
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Software | Managed
  ansible.builtin.include_tasks: '{{ item }}'
  with_items:
    - fish.yml
    - docker.yml
    - nemo.yml

- name: Software | Find all config files
  find:
    paths: '{{ role_path }}/files'
    recurse: false
    file_type: any
    excludes:
      - nemo
      - maya
  register: find

- name: Software | Link config files
  file:
    src: '{{ item.path }}'
    path: ~/.config/{{ item.path | basename }}
    state: link
  with_items: '{{ find.files }}'

- name: Software | Linking maya config files
  file:
    src: '{{ role_path }}/files/maya'
    path: ~/maya
    state: link
