---
- name: Archlinux Setup
  hosts: localhost

  vars_files:
    - packages.yml
    - paths.yml

  tasks:
    - import_tasks: tasks/chaotic-aur.yml
    - import_tasks: tasks/base-packages.yml
    - import_tasks: tasks/dwm.yml
    - import_tasks: tasks/dev-packages.yml
    - import_tasks: tasks/software-packages.yml
    - import_tasks: tasks/firewall.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/appearance.yml
    - import_tasks: tasks/gaming.yml
