include themes/mocha.conf

font_family             JetBrainsMono Nerd Font Mono
font_size               14
confirm_os_window_close 0
enable_audio_bell       no

background_opacity   0.98
window_padding_width 10
box_drawing_scale    0.001, 0.001, 0.001, 0.001

url_style straight
clear_all_shortcuts no
kitty_mod           ctrl+shift

map kitty_mod+i launch --type=overlay-main  /usr/bin/fish -c ~/.config/scripts/tmux-sessionizer

# allow_remote_control socket-only
# listen_on unix:/tmp/kitty


# shell /usr/bin/bash -c  ~/.config/kitty/session.sh
# watcher watcher.py
