---
- name: Appearance | Running Tasks
  with_items:
    - cursor.yml
    # - display_manager.yml
    - fonts.yml
    # - plymouth.yml
    - gtk-theme.yml
  loop_control:
    loop_var: appearance_task
  ansible.builtin.include_tasks: tasks/appearance/{{ appearance_task }}
