---
- name: Chaotic-AUR | Importing primary key
  become: true
  command: pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
  changed_when: false

- name: Chaotic-AUR | Signing primary key
  become: true
  command: pacman-key --lsign-key 3056513887B78AEB
  changed_when: false

- name: Chaotic-AUR | Installing keyring and mirrorlist
  become: true
  command: pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
  changed_when: false

- name: Chaotic-AUR | Checking pacman.conf contents
  command: cat /etc/pacman.conf
  register: pacman_conf_output
  changed_when: false

- name: Chaotic-AUR | Adding repository to pacman.conf
  become: true
  lineinfile:
    path: /etc/pacman.conf
    line: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
    insertafter: EOF
  when: "'[chaotic-aur]' not in pacman_conf_output.stdout"
  changed_when: false
  failed_when: false

- import_tasks: tasks/update.yml
