---
# - name: DWM | Installing xorg packages
#   become: true
#   community.general.pacman:
#     name: '{{xorg_packages}}'
#     state: present
#   changed_when: false

- name: DWM | Installing build dependencies
  become: true
  community.general.pacman:
    name: '{{dwm_deps}}'
    state: present
  changed_when: false

- name: DWM | Building and installing DWM and DWMBLOCKS
  become: true
  loop:
    - dwm
    - dwmblocks
  command:
    cmd: /usr/bin/make clean install
    chdir: '{{ dwm_path }}/{{ item }}'

- name: DWM | Create xsessions
  become: true
  ansible.builtin.file:
    path: /usr/share/xsessions
    state: directory

- name: DWM | Copying session file to xsessions
  become: true
  ansible.builtin.copy:
    src: '{{ dwm_path }}/dwm.desktop'
    dest: /usr/share/xsessions/dwm.desktop

- name: DWM | Copying session executable file to binaries
  become: true
  ansible.builtin.copy:
    src: '{{ dwm_path }}/dwm-session'
    dest: /usr/local/bin/dwm-session
    mode: a+x

- name: DWM | Copying .profile file to home
  ansible.builtin.copy:
    src: '{{ dwm_path }}//profile'
    dest: ~/.profile

- name: DWM | Removing bash profile
  command: 'mv {{ bash_item }} {{ bash_item }}.bak'
  loop_control:
    loop_var: bash_item
  with_items:
    - .bash_profile
    - .bash_history

- name: DWM | Adding executables to .profile
  ansible.builtin.blockinfile:
    prepend_newline: true
    insertafter: EOF
    path: ~/.profile
    block: |-
      if [ -d "{{ playbook_dir }}/{{ dwm_path }}/bin" ]; then
          PATH="{{ playbook_dir }}/{{ dwm_path }}/bin:$PATH"
      fi
