---
- name: UFW Firewall | Installing
  become: true
  community.general.pacman:
    name: ufw
    state: present
  changed_when: false

- name: UFW Firewall | Disabling
  become: true
  community.general.ufw:
    state: disabled

- name: UFW Firewall | Configuring
  become: true
  community.general.ufw: ufw {{ item }}
  with_items:
    - limit 22/tcp
    - allow 80/tcp
    - allow 443/tcp
    - default deny incoming
    - default allow outgoing

- name: UFW Firewall | Enabling
  become: true
  community.general.ufw:
    state: enabled
