---
- name: UFW Firewall | Installing
  become: true
  community.general.pacman:
    name: ufw
    state: present
  changed_when: false

- name: UFW Firewall | Disabling
  become: true
  community.general.ufw:
    state: disabled

- name: UFW Firewall | Configuring rules
  become: true
  community.general.ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  with_items:
    - rule1:
        - rule: limit
        - port: 22
        - proto: tcp

    - rule2:
        - rule: allow
        - port: 80
        - proto: tcp

    - rule3:
        - rule: allow
        - port: 443
        - proto: tcp

- name: UFW Firewall | Configuring defaults
  become: true
  command: ufw {{ item }}
  with_items:
    - default deny incoming
    - default allow outgoing

- name: UFW Firewall | Enabling
  become: true
  community.general.ufw:
    state: enabled
