#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
cd $SCRIPT_DIR

utils="$SCRIPT_DIR/../utils.sh"
source $utils "$@"

font_packages=(
    ttf-jetbrains-mono-nerd
    ttf-firacode-nerd
    ttf-terminus-nerd
    ttf-victor-mono-nerd
    noto-fonts
    noto-fonts-emoji
    noto-fonts-cjk
)

info "Fonts | Installing"
execute sudo pacman -Syu --noconfirm
execute sudo pacman -S ${font_packages[@]} --noconfirm --needed
