#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
cd $SCRIPT_DIR

utils="$SCRIPT_DIR/../utils.sh"
source $utils "$@"

gaming_packages=(
    lib32-vulkan-radeon
    steam
    lutris
    wine-staging
    winetricks
    protontricks
    gamemode
    gamescope
    protonplus
)

lutris_dependencies=(
    lib32-gamemode
    lib32-vkd3d
    python-protobuf
    vkd3d
    vulkan-tools
)

wine_dependencies=(
    alsa-lib
    alsa-plugins
    giflib
    gnutls
    gst-plugins-base-libs
    gtk3
    lib32-alsa-lib
    lib32-alsa-plugins
    lib32-giflib
    lib32-gnutls
    lib32-gst-plugins-base-libs
    lib32-gtk3
    lib32-libpulse
    lib32-libva
    lib32-libxcomposite
    lib32-ocl-icd
    lib32-sdl2
    lib32-sqlite
    lib32-v4l-utils
    lib32-vulkan-icd-loader
    libpulse
    libva
    libxcomposite
    ocl-icd
    sdl2
    sqlite
    v4l-utils
    vulkan-icd-loader
)

info "Gaming | Installing"
execute sudo pacman -Syu --noconfirm
execute sudo pacman -S ${gaming_packages[@]} --noconfirm --needed
execute sudo pacman -S ${lutris_dependencies[@]} --noconfirm --needed
execute sudo pacman -S ${wine_dependencies[@]} --noconfirm --needed
