---
- name: Gaming | Installing gaming packages
  become: true
  kewlfft.aur.aur:
    name: '{{ gaming_packages }}'
    use: yay
    state: present
  changed_when: false

- name: Gaming | Installing wine dependencies
  become: true
  kewlfft.aur.aur:
    name: '{{ wine_dependencies }}'
    use: yay
    state: present
  changed_when: false

- name: Gaming | Installing lutris dependencies
  become: true
  kewlfft.aur.aur:
    name: '{{ lutris_dependencies }}'
    use: yay
    state: present
  changed_when: false
