---
- name: Gaming | Installing gaming packages
  become: true
  community.general.pacman:
    name: '{{ gaming_packages }}'
    state: present
  changed_when: false

- name: Gaming | Installing wine dependencies
  become: true
  community.general.pacman:
    name: '{{ wine_dependencies }}'
    state: present
  changed_when: false

- name: Gaming | Installing lutris dependencies
  become: true
  community.general.pacman:
    name: '{{ lutris_dependencies }}'
    state: present
  changed_when: false
