PATH=$HOME/.local/bin:$PATH
PATH=$HOME/.config/scripts:$PATH
PATH=$HOME/.cargo/bin:$PATH

EDITOR=nvim
TMPDIR=/tmp

XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state
XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache

ZDOTDIR=$XDG_CONFIG_HOME/zsh
MAYA_APP_DIR=$XDG_CONFIG_HOME/maya

QT_QPA_PLATFORMTHEME=hyprqt6engine
QT_SCALE_FACTOR=1

# vim: set ft=bash
