---
- name: DWM | Install build dependencies
  become: true
  community.general.pacman:
    name:
      - base-devel
      - libx11
      - libxft
      - libxinerama
      - freetype2
      - fontconfig
    state: present
