---
- name: 'DWM | Checking for Distribution Config: {{ ansible_distribution }}'
  ansible.builtin.stat:
    path: '{{ role_path }}/tasks/{{ ansible_distribution }}.yml'
  register: dwm_distribution_config

- name: 'DWM | Run Tasks: {{ ansible_distribution }}'
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yml'
  when: dwm_distribution_config.stat.exists

- name: DWM | Building and installing DWM and DwmBlocks
  become: true
  loop:
    - dwm
    - dwmblocks
  command:
    cmd: /usr/bin/make clean install
    chdir: '{{ role_path }}/files/{{ item }}'

- name: DWM | Create xsessions
  become: true
  ansible.builtin.file:
    path: /usr/share/xsessions
    state: directory

- name: DWM | Copying session file to xsessions
  become: true
  ansible.builtin.copy:
    src: dwm.desktop
    dest: /usr/share/xsessions/dwm.desktop

- name: DWM | Copying session executable file to binaries
  become: true
  ansible.builtin.copy:
    src: dwm-session
    dest: /usr/local/bin/dwm-session
    mode: a+x

- name: DWM | Copying .profile file to home
  ansible.builtin.copy:
    src: .profile
    dest: ~/.profile

- name: DWM | Sourcing .profile in .bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: '[[ -f ~/.profile ]] && . ~/.profile'
    insertafter: EOF
  when: lookup('file', '~/.bash_profile') is not search('. ~/.profile')

- name: DWM | Adding executables to .profile
  ansible.builtin.blockinfile:
    prepend_newline: true
    insertafter: EOF
    path: ~/.profile
    block: |-
      if [ -d "{{ role_path }}/files/bin" ]; then
          PATH="{{ role_path }}/files/bin:$PATH"
      fi
