---
- name: 'DWM | Checking for Distribution Config: {{ ansible_distribution }}'
  ansible.builtin.stat:
    path: '{{ role_path }}/tasks/{{ ansible_distribution }}.yml'
  register: dwm_distribution_config

- name: 'DWM | Run Tasks: {{ ansible_distribution }}'
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yml'
  when: dwm_distribution_config.stat.exists

- name: DWM | Build and install DWM and DwmBlocks
  become: true
  loop:
    - dwm
    - dwmblocks
  community.general.make:
    target: install
    chdir: '{{ role_path }}/files/{{ item }}'
    make: /usr/bin/make

- name: DWM | Move session file to xsessions
  ansible.builtin.copy:
    src: dwm.desktop
    dest: /usr/share/xsessions/dwm.desktop

- name: DWM | Move executable file to binaries
  ansible.builtin.copy:
    src: dwm-session
    dest: /usr/local/bin/dwm-session
    mode: a+x
