# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

setw -g mode-keys vi
# set -g status off

# reload conf
unbind r
unbind '"'
unbind %

bind r source-file ~/.config/tmux/tmux.conf

# split panes using | and -
bind H split-window -v
bind V split-window -h

bind-key P set-option -g status

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator

# decide whether we're in a Vim process
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
is_poetry="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?poetry$'"

bind -n C-h run "($is_poetry && tmux send-keys C-h) || ($is_vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "($is_vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "($is_vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "($is_poetry && tmux send-keys C-l) || ($is_vim && tmux send-keys C-l) || tmux select-pane -R"

bind C-l send-keys 'C-l'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# switch windows alt+number
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

bind-key c new-window
bind-key x kill-pane

set -s escape-time 0
# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename on
set-option -g automatic-rename on 
set -g renumber-windows on


set-option -sa terminal-overrides ",xterm-kitty:RGB"

#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour8'


# BG_MAIN="#1E1E2E"
# BG_COLOR="#29293F"
# BG_DARK="#181825"
# BG_MID="#1E1E2E"

#catpuccin
BG_LIGHT_02="#585b70"
BG_LIGHT_01="#45475a"
BG_LIGHT_00="#313244"
BG_MAIN="#1E1E2E"
BG_DARK_00="#181825"
BG_DARK_01="#11111b"

#gruvbox-material
# BG_LIGHT_02="#928374"
# BG_LIGHT_01="#45475a"
# BG_LIGHT_00="#212425"
# BG_MAIN="#1D2021"
# BG_DARK_00="#141617"
# BG_DARK_01="#212425"


# panes
set -g pane-border-style 'fg=#{BG_DARK_01} bg=#{BG_MAIN}'
set -g pane-active-border-style 'bg=#{BG_MAIN} fg=colour4'

# statusbar
set -g status-position bottom
set -g status-justify centre 
set -g status-bg $BG_DARK_01
set -g status-fg $BG_LIGHT_00

# set -g status-right "\
# #[bg=#{BG_DARK_00}, fg=cyan]▐\
# #[fg=#{BG_DARK_01}, bg=cyan] \
# #[fg=cyan, bg=#{BG_LIGHT_00} bold] #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) \
# #[bg=pink, fg=#{BG_DARK_00}]▌#[fg=#{BG_DARK_01}]󰥔 #[fg=pink, bg=#{BG_LIGHT_00}, bold] %H:%M " 

# set -g status-left "\
# #[bg=#{BG_DARK_00}, fg=cyan]▐\
# #[fg=#{BG_DARK_01}, bg=cyan] \
# #[fg=cyan, bg=#{BG_LIGHT_00} bold] #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)\
# #[fg=#{BG_DARK_00}, bg=#{BG_LIGHT_00}]▐"

set -g status-left ""
set -g status-right ""

set -g status-left-length 50
set -g status-right-length 50


set-window-option -g window-status-separator " " #'▌'

setw -g window-status-format '\
#[fg=#{BG_LIGHT_02}, bg=#{BG_MAIN}] #I \
#[fg=#{BG_LIGHT_02}, bg=#{BG_DARK_01}] #W '

setw -g window-status-current-format '\
#[bg=colour12, fg=#{BG_DARK_00}, bold]  \
#[fg=colour12, bg=#{BG_MAIN}] #W '


# messages
set -g message-style 'fg=yellow bg=#{BG_DARK_00} bold'
set -g message-command-style 'fg=yellow bg=#1c1c1c bold dim'

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
