# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

setw -g mode-keys vi
# set -g status off


source-file ~/.config/tmux/keybinds.conf

set -s escape-time 0
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename on
set-option -g automatic-rename on 
set -g renumber-windows on


set-option -sa terminal-overrides ",xterm-kitty:RGB"

#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour8'


# BG_MAIN="#1E1E2E"
# BG_COLOR="#29293F"
# BG_DARK="#181825"
# BG_MID="#1E1E2E"

#catpuccin
BG_LIGHT_02="#585b70"
BG_LIGHT_01="#45475a"
BG_LIGHT_00="#313244"
BG_MAIN="#1E1E2E"
BG_DARK_00="#181825"
BG_DARK_01="#11111b"

#gruvbox-material
# BG_LIGHT_02="#928374"
# BG_LIGHT_01="#45475a"
# BG_LIGHT_00="#212425"
# BG_MAIN="#1D2021"
# BG_DARK_00="#141617"
# BG_DARK_01="#212425"


# panes
set -g pane-border-style 'fg=#{BG_DARK_01} bg=#{BG_MAIN}'
set -g pane-active-border-style 'bg=#{BG_MAIN} fg=colour4'

# statusbar
set -g status-position top 
set -g status-justify left 
set -g status-bg $BG_DARK_01
set -g status-fg $BG_LIGHT_00

set -g status-left "\
#[bg=#{BG_MAIN}, fg=red]\
#[fg=#{BG_DARK_01}, bg=red] \
#[bg=#181826, fg=white, bold] #{session_name} "

set -g status-right '#[fg=#{BG_DARK_01}, bg=#{BG_MAIN}]' 

set -g status-left-length 50
set -g status-right-length 20


set-window-option -g window-status-separator "" #'▌'

setw -g window-status-format '#[fg=#{BG_LIGHT_02}, bg=#{BG_DARK_00}] #I '
setw -g window-status-current-format '#[bg=colour12, fg=#{BG_DARK_01}, bold] #I '


# messages
set -g message-style 'fg=yellow bg=#{BG_DARK_00} bold'
set -g message-command-style 'fg=yellow bg=#1c1c1c bold dim'

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
