music_directory      "$XDG_MUSIC_DIR"
playlist_directory   "$XDG_MUSIC_DIR/playlists"
db_file              "$XDG_CACHE_HOME/mpd/database"
log_file             "$XDG_CACHE_HOME/mpd/log"
pid_file             "$XDG_CACHE_HOME/mpd/pid"
state_file           "$XDG_CACHE_HOME/mpd/state"
sticker_file         "$XDG_CACHE_HOME/mpd/sticker.sql"

bind_to_address      "127.0.0.1"
port                 "6600"

auto_update          "yes"
restore_paused       "yes"

follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

audio_output {
    type        "pulse"
    name        "My PipeWire Output"
}

# audio_output {
#     type             "alsa"
#     name             "My ALSA Device"
#     device           "hw:0,0"
#     mixer_type       "software" # use "hardware" if your volume keys directly control the sound card
# }

# audio_output {
#     type             "httpd"
#     name             "Local HTTP Stream"
#     encoder          "vorbis" # use "lame" for MP3/iOS compatibility
#     port             "8000"
#     bitrate          "128"
#     format           "44100:16:2"
#     max_clients      "4"
# }
