#!/usr/bin/env bash

EVENTS=(
    layout_change_event
    tag_change_event
    client_focus_change_event
    monitor_focus_change_event
    focused_title_change_event
    focused_state_change_event
)

function get-monitor-data() {
    dwm-msg get_monitors | jq -cr --unbuffered
}

function get-layout-symbols() {
    local data=$1
    echo "$data" | jq -rc '[.[] |  .layout.symbol.current ]'
}

TAG_NAMES=(1 2 3 4 5 6 7 8 9)

function generate-tags() {
    local data=$1
    local length selected occupied urgent monitor_data

    length="$(echo "$data" | jq "length")"
    for ((i = 0; i < length; i++)); do
        monitor_data="$(echo "$data" | jq -rc ".[] | select(.num == $i)")"
        read -r selected occupied urgent < <(echo "$monitor_data" |
            jq -r '.tag_state | "\(.selected) \(.occupied) \(.urgent)"')

        echo -n "(box :class 'tag-container' :orientation 'v' :space-evenly false"

        for j in {0..8}; do
            mask=$((1 << j))

            if (((selected & mask) || (occupied & mask) || (urgent & mask))); then
                class="tag-occupied"
                [[ $((selected & mask)) -ne 0 ]] && class="tag-selected"
                [[ $((urgent & mask)) -ne 0 ]] && class="tag-urgent"

                tag_name="${TAG_NAMES[$j]}"
                echo -n "(button :class '$class' :onclick 'dwm-msg run_command view $mask' '$tag_name') "
            fi
        done
        echo ")"
    done | jq -R . | jq -sc
}

function format() {
    echo -n "\"$1\" : $2"
}

function update() {
    local data
    data="$(get-monitor-data)"

    if [[ -z "$data" ]]; then
        return
    fi

    generate-tags "$data"

    echo -n "{"
    format layouts "$(get-layout-symbols "$data"),"
    format tags "$(generate-tags "$data")"
    echo "}"
}

dwm-msg subscribe "${EVENTS[@]}" | jq -cr --unbuffered | while read -r _; do
    update
done
