#!/usr/bin/env bash

MONITOR=${1:-0}
TAG_NAMES=(1 2 3 4 5 6 7 8 9)

generate_widget() {
    local monitor_data
    monitor_data=$(dwm-msg get_monitors | jq -c ".[] | select(.num == $MONITOR)")

    if [[ -z "$monitor_data" ]]; then
        return
    fi

    read -r selected occupied urgent < <(echo "$monitor_data" |
        jq -r '.tag_state | "\(.selected) \(.occupied) \(.urgent)"')

    echo -n "(box :class 'tag-container' :orientation 'v' "

    for i in {0..8}; do
        mask=$((1 << i))

        if (((selected & mask) || (occupied & mask) || (urgent & mask))); then
            class="tag-occupied"
            [[ $((selected & mask)) -ne 0 ]] && class="tag-selected"
            [[ $((urgent & mask)) -ne 0 ]] && class="tag-urgent"

            tag_name="${TAG_NAMES[$i]}"
            echo -n "(button :class '$class' :onclick 'dwm-msg run_command view $mask' '$tag_name') "
        fi
    done

    echo ")"
}

generate_widget

dwm-msg subscribe tag_change_event | while read -r _; do
    generate_widget
done
