//Maya Preference 2022 (Release 1)
//
//
evalDeferred("autoLoadPlugin(\"\", \"matrixNodes\", \"matrixNodes\")");
evalDeferred("autoLoadPlugin(\"\", \"CharcoalEditor2\", \"CharcoalEditor2\")");
evalDeferred("autoLoadPlugin(\"\", \"quatNodes\", \"quatNodes\")");
evalDeferred("autoLoadPlugin(\"\", \"fbxmaya\", \"fbxmaya\")");
evalDeferred("autoLoadPlugin(\"\", \"modelingToolkit\", \"modelingToolkit\")");
