"$schema" = 'https://starship.rs/config-schema.json'

format = """\
$directory\
$git_branch\
$git_commit\
$git_sate\
$python\
$c\
$cpp\
$dotnet\
$lua
$sudo$jobs$status$character"""

add_newline = false

[fill]
symbol = '╴'

[status]
format = '[\[$status\] ]($style)'
style = 'red'
disabled = false

[sudo]
disabled = false
style = 'yellow'
format = '[$symbol ]($style)'
symbol = '󱦚'

[character]
success_symbol = '[❯](bold white)'

[jobs]
symbol = '󱁤'

[directory]
truncation_length = 4
read_only = "󰦝 "
style = 'bold blue'
format = '[$read_only]($read_only_style)[ $path]($style)'

[git_branch]
format = ' [➤](bold black) [$symbol$branch(:$remote_branch)]($style)'
style = "bold green"

[git_commit]
format = ' [\($hash$tag\)]($style)'
style = "red"

[python]
format = ' [➤](bold black) [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ""

[dotnet]
style = 'blue'
format = ' [➤](bold black) [$symbol ($version )($tfm )]($style)'
version_format = 'v${major}.${minor}'
symbol = ''

[c]
style = 'blue'
commands = [ [ 'clang', '--version' ], [ 'cc', '--version' ], [ 'gcc', '--version' ] ]
format = ' [➤](bold black) [$symbol $name $version]($style)'
version_format = 'v${major}.${minor}'
symbol = ''

[cpp]
style = 'blue'
disabled = false
commands = [ [ 'clang++', '--version' ], [ 'c++', '--version' ], [ 'g++', '--version' ] ]
format = ' [➤](bold black) [$symbol $name $version]($style)'
version_format = 'v${major}.${minor}'
symbol = ''

[lua]
format = ' [➤](bold black) [$symbol ($version )]($style)'
version_format = 'v${major}.${minor}'
symbol = ''
