"$schema" = 'https://starship.rs/config-schema.json'

format = """\
$directory\
$git_branch\
$git_commit\
$git_sate\
$fill \
$python\
$c\
$cpp\
$dotnet\
$lua
$sudo$jobs$status$character
"""

[fill]
symbol = '╴'

[status]
format = '[\[$status\] ]($style)'
style = 'red'
disabled = false

[sudo]
disabled = false
style = 'yellow'
format = '[$symbol ]($style)'
symbol = '󱦚'

[jobs]
symbol = '󱁤'


[directory]                   
truncation_length = 8         
home_symbol = '~'             
style = 'fg:blue bold'        
format = '[ $path ]($style)' 

[git_branch]
format = '[┃](fg:black) [$symbol$branch(:$remote_branch)]($style) '
style = "bold green"

[git_commit]
style = "purple"

[python]
format = '[${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ""

[dotnet]
format = '[$symbol ($version )($tfm )]($style)'
version_format = 'v${major}.${minor}'
symbol = ''
