"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$git_branch$git_commit$python
$sudo$shell$jobs$character"""

add_newline = true

[shell]
disabled = false
fish_indicator = ""
bash_indicator = " bash "
format = "[$indicator]($style)"
style = "fg:#A1ABA0"


[directory]
truncation_length = 8
home_symbol = "~"
style = "fg:blue bold"
format = "[ $path ]($style bold)"


[python]
style = "fg:#C98F6C bold"
symbol = "[ ]($style)"
format = "$symbol[$version](bold)[ $virtualenv]($style)"

[git_branch]
style = "fg:green bold"
symbol = ""
format = "[$symbol $branch ]($style)"
only_attached = true

[git_commit]
style = "fg:green bold"
format = '[󰜘 $hash$tag]($style) '
tag_symbol = " - "
tag_disabled = false
only_detached = true

[character]
success_symbol = '[➤](#A1ABA0)'
error_symbol = '[](#c76b77)'
vimcmd_symbol = '[](#F9E2AF)'

[jobs]
symbol = '[](#A6E3A1)'
symbol_threshold = 1

[sudo]
style = 'yellow'
symbol = ''
format = "[$symbol ]($style)"
disabled = false
