map kitty_mod+i launch --type=overlay-main /bin/sh -c 'tmux new-session -As "Dotfiles" tmux-sessionizer ~/.config/dotfiles/dotfiles/'
map kitty_mod+n launch --type=overlay-main /bin/sh -c 'tmux new-session -As "Notes" tmux-sessionizer /media/storage/development/notes/'
map kitty_mod+m launch --type=overlay-main /bin/sh -c 'tmux new-session -As "Maya" tmux-sessionizer /media/storage/development/maya/'
map kitty_mod+u launch --type=overlay-main /bin/sh -c 'tmux new-session -As "Unity" tmux-sessionizer /media/storage/development/unity/projects/'
map kitty_mod+g launch --type=overlay-main /bin/sh -c 'tmux new-session -As "Unity" tmux-sessionizer /media/storage/development/godot/'

