"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$git_branch$python
$shell$jobs$character"""

add_newline = true

[shell]
disabled = false
fish_indicator = ""
bash_indicator = " bash "
format = "[$indicator]($style)"
style = "fg:#A1ABA0"


[directory]
truncation_length = 8
home_symbol = "~"
style = "fg:blue bold"
format = "[ $path ]($style bold)"


[python]
style = "fg:#C98F6C bold"
symbol = "[ ]($style)"
format = "$venv$symbol[$version](bold)"

[git_branch]
style = "fg:green bold"
symbol = ""
format = "[$symbol $branch ]($style)"

[character]
success_symbol = '[➤](#A1ABA0)'
error_symbol = '[](#c76b77)'
vimcmd_symbol = '[](#F9E2AF)'

[jobs]
symbol = '[](#A6E3A1)'
symbol_threshold = 1
