[colors]
background = '#1C1917'
foreground = '#9A8F8A'
cursor_bg = '#837771'
cursor_border = '#837771'
cursor_fg = '#1C1917'
ansi = [
	'#141110',
	'#af9da2',
	'#a1aba0',
	'#cfc5af',
	'#81a2be',
	'#e2d4df',
	'#b0c4c1',
	'#B4BDC3',
]
brights = [
	'#25211E',
	'#af9da2',
	'#a1aba0',
	'#cfc5af',
	'#81a2be',
	'#e2d4df',
	'#b0c4c1',
	'#9A8F8A',
]
