---
- name: Fonts | Installing extra fonts
  become: true
  loop:
    - ttf-jetbrains-mono-nerd
    - ttf-firacode-nerd
    - noto-fonts
  loop_control:
    loop_var: font

  community.general.pacman:
    name: '{{ font }}'
    state: present

  when: ansible_facts['os_family'] == 'Archlinux'

- name: Fonts | Creating user fonts directory
  ansible.builtin.file:
    path: ~/.config/fonts
    state: directory

- name: Fonts | Copying fonts
  ansible.builtin.copy:
    src: patched
    dest: ~/.local/share/fonts/patched
