
[colors]
foreground = "#9A8F8A"
background = "#161617"

cursor_fg = "#161617"
cursor_bg = "#b39580"
cursor_border = "#b39580"

selection_bg = "#25211E"

ansi = [
	"#131314",
	"#EA83A5",
	"#90B99F",
	"#E6B99D",
	"#ACA0CF",
	"#E19ECA",
	"#8EA4A2",
	"#9a8f8a",
]
brights = [
	"#2A2A2D",
	"#F591B2",
	"#9DC6AC",
	"#F0C5A9",
	"#B9AEDA",
	"#ECAAD6",
	"#8EA4A2",
	"#9E9794",
]
