[colors]
foreground = "#9A8F8A"
background = "#161617"

cursor_fg = "#161617"
cursor_bg = "#be8c8c"
cursor_border = "#be8c8c"

selection_bg = "#232325"

ansi = [
	"#1f1f22",
	"#945B5B",
	"#889b7d",
	"#B7927B",
	"#627691",
	"#be8c8c",
	"#8EA4A2",
	"#90847f",
]

brights = [
	"#393946",
	"#9c6363",
	"#8f9d85",
	"#b99b88",
	"#6e7f96",
	"#baa0a7",
	"#98a9a7",
	"#9A8F8A",
]
