[colors]
foreground = "#9A8F8A"
background = "#161617"

cursor_fg = "#161617"
cursor_bg = "#b39580"
cursor_border = "#b39580"

selection_bg = "#25211E"

ansi = [
	"#0D0D0D",
	"#af6a6a",
	"#9cb380",
	"#CB775D",
	"#809bb3",
	"#977b9f",
	"#97B7B3",
	"#9a8f8a",
]
brights = [
	"#443b3b",
	"#C5727A",
	"#B1C89D",
	"#D79784",
	"#81A1C1",
	"#BE9DB8",
	"#9FC6C5",
	"#9E9794",
]
