---
- name: 'Fonts | Checking for Distribution Config: {{ ansible_distribution }}'
  ansible.builtin.stat:
    path: '{{ role_path }}/tasks/{{ ansible_distribution }}.yml'
  register: fonts_distribution_config

- name: 'Fonts | Run Tasks: {{ ansible_distribution }}'
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yml'
  when: fonts_distribution_config.stat.exists

- name: Fonts | Creating user fonts directory
  ansible.builtin.file:
    path: ~/.config/fonts
    state: directory

- name: Fonts | Copying fonts
  ansible.builtin.copy:
    src: patched
    dest: ~/.local/share/fonts/patched
